import React, { useState } from 'react';
import { PageLayout } from '@/components/layout/PageLayout';
import { mockPrivacyAssessment } from '@/data/mockData';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import {
  Shield,
  CheckCircle2,
  XCircle,
  AlertTriangle,
  Activity,
  Lock,
  Eye,
  Fingerprint,
  RefreshCw,
  FileText,
  Download
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Progress } from '@/components/ui/progress';
import { cn } from '@/lib/utils';
import { Badge } from '@/components/ui/badge';
import { useToast } from '@/hooks/use-toast';
import { format } from 'date-fns';
import { logSecureAudit } from '@/lib/crypto/audit-hashing';


export default function Security() {
  const { user, profile } = useAuth();
  const { toast } = useToast();
  const [assessment, setAssessment] = useState(mockPrivacyAssessment);
  const [isScanning, setIsScanning] = useState(false);
  const [auditLogs, setAuditLogs] = useState([
    { action: 'Privacy assessment completed', time: '2 minutes ago', user: 'System' },
    { action: 'Traffic shaping enabled', time: '1 hour ago', user: 'Admin' },
    { action: 'Security scan initiated', time: '3 hours ago', user: 'Officer Singh' },
    { action: 'Defense configuration updated', time: '1 day ago', user: 'Admin' },
  ]);

  const runPrivacyAudit = async () => {
    setIsScanning(true);

    // Simulate ML-based privacy assessment
    await new Promise(resolve => setTimeout(resolve, 3000));

    const newScore = Math.floor(Math.random() * 30) + 50;

    setAssessment({
      ...assessment,
      timestamp: new Date(),
      riskScore: newScore,
    });

    // Log the audit
    if (user) {
      await logSecureAudit('Privacy audit completed', {
        riskScore: newScore,
        timestamp: new Date().toISOString()
      }, user.id);
    }


    setAuditLogs(prev => [
      { action: 'Privacy audit completed', time: 'Just now', user: profile?.name || 'System' },
      ...prev,
    ]);

    setIsScanning(false);

    toast({
      title: 'Privacy Audit Complete',
      description: `Risk Score: ${newScore}/100`,
    });
  };

  const generatePDFReport = () => {
    // Create PDF content
    const reportContent = `
PROJECT CHAMELEON - PRIVACY ASSESSMENT REPORT
=============================================
Generated: ${format(new Date(), 'PPpp')}
Generated By: ${profile?.name || 'System'}

EXECUTIVE SUMMARY
-----------------
Privacy Risk Score: ${assessment.riskScore}/100
Assessment Status: ${assessment.riskScore < 60 ? 'ACCEPTABLE' : 'NEEDS ATTENTION'}

DETECTED FINGERPRINTS
---------------------
${assessment.websiteFingerprint.map(site => `• ${site}`).join('\n')}

BEHAVIOR PATTERNS
-----------------
${assessment.behaviorPatterns.map(pattern => `• ${pattern}`).join('\n')}

DEFENSE STATUS
--------------
• Packet Padding: ${assessment.defenseStatus.packetPadding ? 'ENABLED' : 'DISABLED'}
• Traffic Shaping: ${assessment.defenseStatus.trafficShaping ? 'ENABLED' : 'DISABLED'}
• Randomized Delays: ${assessment.defenseStatus.randomizedDelays ? 'ENABLED' : 'DISABLED'}

RECOMMENDATIONS
---------------
${assessment.recommendations.map((rec, i) => `${i + 1}. ${rec}`).join('\n')}

---
Report generated by Project Chameleon
Tamil Nadu Police Cyber Crime Wing
Team CIT - TN Police Hackathon 2025
    `;

    // Create and download PDF (as text file for simplicity)
    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `privacy-report-${format(new Date(), 'yyyy-MM-dd-HHmmss')}.txt`;
    a.click();
    window.URL.revokeObjectURL(url);

    toast({
      title: 'Report Generated',
      description: 'Privacy assessment report has been downloaded',
    });

    // Log the action
    if (user) {
      logSecureAudit('PDF report generated', { riskScore: assessment.riskScore }, user.id);
    }


    setAuditLogs(prev => [
      { action: 'PDF report generated', time: 'Just now', user: profile?.name || 'System' },
      ...prev,
    ]);
  };

  const getRiskColor = (score: number) => {
    if (score < 30) return 'text-status-online';
    if (score < 60) return 'text-status-warning';
    if (score < 80) return 'text-chameleon-orange';
    return 'text-destructive';
  };

  const toggleDefense = async (key: string) => {
    const newStatus = !assessment.defenseStatus[key as keyof typeof assessment.defenseStatus];

    setAssessment({
      ...assessment,
      defenseStatus: {
        ...assessment.defenseStatus,
        [key]: newStatus,
      },
    });

    const label = key === 'packetPadding' ? 'Packet Padding' :
      key === 'trafficShaping' ? 'Traffic Shaping' : 'Randomized Delays';

    toast({
      title: `${label} ${newStatus ? 'Enabled' : 'Disabled'}`,
      description: newStatus ? 'Defense mechanism activated' : 'Defense mechanism deactivated',
    });

    if (user) {
      await logSecureAudit(`${label} ${newStatus ? 'enabled' : 'disabled'}`, {
        defense: key,
        enabled: newStatus
      }, user.id);
    }


    setAuditLogs(prev => [
      { action: `${label} ${newStatus ? 'enabled' : 'disabled'}`, time: 'Just now', user: profile?.name || 'System' },
      ...prev,
    ]);
  };

  const defenseItems = [
    {
      key: 'packetPadding',
      label: 'Packet Padding',
      description: 'Add dummy data to normalize packet sizes',
      icon: Shield,
    },
    {
      key: 'trafficShaping',
      label: 'Traffic Shaping',
      description: 'Normalize traffic patterns to prevent fingerprinting',
      icon: Activity,
    },
    {
      key: 'randomizedDelays',
      label: 'Randomized Delays',
      description: 'Add random delays between requests',
      icon: RefreshCw,
    },
  ];

  return (
    <PageLayout title="Security" subtitle="Privacy assessment & defense">
      <div className="p-6 space-y-6">
        {/* Privacy Audit Section */}
        <div className="bg-slate-900/80 border border-slate-700/50 rounded-xl p-6 space-y-6 backdrop-blur-sm">
          <div className="flex items-start justify-between">
            <div>
              <h2 className="text-xl font-semibold flex items-center gap-2 text-white">
                <Fingerprint className="w-6 h-6 text-cyan-400" />
                Privacy Assessment
              </h2>
              <p className="text-sm text-slate-400 mt-1">
                Analyze network traffic privacy vulnerabilities
              </p>
            </div>
            <Button
              onClick={runPrivacyAudit}
              disabled={isScanning}
              className="bg-gradient-to-r from-cyan-500 to-emerald-500 hover:from-cyan-600 hover:to-emerald-600">
              {isScanning ? (
                <>
                  <RefreshCw className="w-4 h-4 mr-2 animate-spin" />
                  Scanning...
                </>
              ) : (
                <>
                  <Eye className="w-4 h-4 mr-2" />
                  Run Privacy Audit
                </>
              )}
            </Button>
          </div>

          {/* Risk Score */}
          <div className="grid md:grid-cols-2 gap-6">
            <div className="space-y-4">
              <h3 className="font-medium">Privacy Risk Score</h3>
              <div className="flex items-center gap-6">
                <div className={cn(
                  "text-5xl font-bold",
                  getRiskColor(assessment.riskScore)
                )}>
                  {assessment.riskScore}
                </div>
                <div className="flex-1 space-y-2">
                  <Progress value={assessment.riskScore} className="h-3" />
                  <div className="flex justify-between text-xs text-muted-foreground">
                    <span>Low Risk</span>
                    <span>High Risk</span>
                  </div>
                </div>
              </div>
              <p className="text-sm text-muted-foreground">
                Last assessment: {assessment.timestamp.toLocaleString()}
              </p>
            </div>

            {/* Fingerprint Detection */}
            <div className="space-y-4">
              <h3 className="font-medium">Detected Fingerprints</h3>
              <div className="flex flex-wrap gap-2">
                {assessment.websiteFingerprint.map((site, i) => (
                  <Badge key={i} variant="secondary" className="text-sm">
                    {site}
                  </Badge>
                ))}
              </div>
              <div className="space-y-2">
                <h4 className="text-sm font-medium text-muted-foreground">Behavior Patterns</h4>
                {assessment.behaviorPatterns.map((pattern, i) => (
                  <p key={i} className="text-sm text-muted-foreground">• {pattern}</p>
                ))}
              </div>
            </div>
          </div>
        </div>

        {/* Defense Configuration */}
        <div className="bg-slate-900/80 border border-slate-700/50 rounded-xl p-6 space-y-6 backdrop-blur-sm">
          <h2 className="text-xl font-semibold flex items-center gap-2 text-white">
            <Shield className="w-6 h-6 text-cyan-400" />
            Defense Configuration
          </h2>

          <div className="grid md:grid-cols-3 gap-4">
            {defenseItems.map((item) => {
              const isEnabled = assessment.defenseStatus[item.key as keyof typeof assessment.defenseStatus];
              const Icon = item.icon;

              return (
                <div
                  key={item.key}
                  className={cn(
                    "p-4 rounded-lg border transition-all cursor-pointer",
                    isEnabled
                      ? "border-status-online/50 bg-status-online/5"
                      : "border-border hover:border-primary/50"
                  )}
                  onClick={() => toggleDefense(item.key)}
                >
                  <div className="flex items-center justify-between mb-3">
                    <Icon className={cn(
                      "w-5 h-5",
                      isEnabled ? "text-status-online" : "text-muted-foreground"
                    )} />
                    {isEnabled ? (
                      <CheckCircle2 className="w-5 h-5 text-status-online" />
                    ) : (
                      <XCircle className="w-5 h-5 text-muted-foreground" />
                    )}
                  </div>
                  <h3 className="font-medium text-sm">{item.label}</h3>
                  <p className="text-xs text-muted-foreground mt-1">{item.description}</p>
                </div>
              );
            })}
          </div>
        </div>

        {/* Recommendations */}
        <div className="bg-slate-900/80 border border-slate-700/50 rounded-xl p-6 space-y-4 backdrop-blur-sm">
          <h2 className="text-xl font-semibold flex items-center gap-2 text-white">
            <AlertTriangle className="w-6 h-6 text-amber-400" />
            Recommendations
          </h2>

          <div className="space-y-3">
            {assessment.recommendations.map((rec, i) => (
              <div key={i} className="flex items-start gap-3 p-3 bg-muted/50 rounded-lg">
                <div className="w-6 h-6 rounded-full bg-primary/20 flex items-center justify-center flex-shrink-0">
                  <span className="text-xs font-bold text-primary">{i + 1}</span>
                </div>
                <p className="text-sm">{rec}</p>
              </div>
            ))}
          </div>

          <div className="pt-4">
            <Button variant="outline" onClick={generatePDFReport}>
              <Download className="w-4 h-4 mr-2" />
              Generate PDF Report
            </Button>
          </div>
        </div>

        {/* Audit Trail */}
        <div className="bg-slate-900/80 border border-slate-700/50 rounded-xl p-6 space-y-4 backdrop-blur-sm">
          <h2 className="text-xl font-semibold flex items-center gap-2 text-white">
            <Lock className="w-6 h-6 text-blue-400" />
            Audit Trail
          </h2>

          <div className="space-y-2">
            {auditLogs.map((log, i) => (
              <div key={i} className="flex items-center justify-between py-2 border-b border-border/50 last:border-0">
                <div className="flex items-center gap-3">
                  <div className="w-2 h-2 rounded-full bg-chameleon-blue" />
                  <span className="text-sm">{log.action}</span>
                </div>
                <div className="flex items-center gap-4 text-sm text-muted-foreground">
                  <span>{log.user}</span>
                  <span>{log.time}</span>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div >
    </PageLayout >
  );
}
